version: '3.1'


services:
  pg_db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432