spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      username: mongod
      password: mongod
      authentication-database: admin

  main:
    banner-mode: off

logging:
  level:
    org.springframework: ERROR
